/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/a4dfa7b2-4c82-4bc7-ae69-ec774e7ba0a7 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight led1;
  CloudLight led2;
  CloudLight led3;
  CloudLight led4;
  CloudTemperatureSensor temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#include <DHTesp.h>
#define DHTPIN 16
#define DHTTYPE DHT11
DHTesp dht;
const int btn[4] = {13,12,14,27};
const int out[4] = {26,25,33,32};
unsigned long timeDelay = millis();
unsigned long timeRead = millis();
bool update=0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  dht.setup(DHTPIN, DHTesp::DHTTYPE);
  for(int i;i<4;i++){
    pinMode(btn[i],INPUT_PULLUP);
    attachInterrupt(btn[i],handleBtn,FALLING);
    pinMode(out[i],OUTPUT);
  }
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  if(millis()-timeRead>1000){
    float t = dht.getTemperature();
    temperature = t;
    timeRead = millis();
  }
  if(update==1){
    led1 = digitalRead(out[0]);
    led2 = digitalRead(out[1]);
    led3 = digitalRead(out[2]);
    led4 = digitalRead(out[3]);
    update=0;
  }
}

ICACHE_RAM_ATTR void handleBtn(){
  if(millis()-timeDelay>500){
    for(int i;i<4 ;i++){
      bool btnState = digitalRead(btn[i]);
      if(btnState==0){
        digitalWrite(out[i],!digitalRead(out[i]));
      }
    }
    update = 1;
    timeDelay = millis();
  }
}
/*
  Since Led1 is READ_WRITE variable, onLed1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed1Change()  {
  // Add your code here to act upon Led1 change
  digitalWrite(out[0],led1);
}

/*
  Since Led2 is READ_WRITE variable, onLed2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed2Change()  {
  // Add your code here to act upon Led2 change
  digitalWrite(out[1],led2);
}

/*
  Since Led3 is READ_WRITE variable, onLed3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed3Change()  {
  // Add your code here to act upon Led3 change
  digitalWrite(out[2],led3);
}

/*
  Since Led4 is READ_WRITE variable, onLed4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed4Change()  {
  // Add your code here to act upon Led4 change
  digitalWrite(out[3],led4);
}

/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
  // Add your code here to act upon Temperature change
}
